import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../api';
import Layout from '../components/Layout';
import DragDropUpload from '../components/DragDropUpload';

export default function ProjectSetup() {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    name: '',
    brand_name: '',
    niche: '',
    product_description: '',
    sales_page_content: '',
  });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  // Sales page upload state
  const [salesInputMode, setSalesInputMode] = useState('upload'); // 'upload' or 'paste'
  const [uploadedFile, setUploadedFile] = useState(null);

  // Auto-describe state
  const [describing, setDescribing] = useState(false);
  const [descAutoGenerated, setDescAutoGenerated] = useState(false);

  const handleChange = (e) => {
    setForm(prev => ({ ...prev, [e.target.name]: e.target.value }));
    if (e.target.name === 'product_description') {
      setDescAutoGenerated(false);
    }
  };

  // Auto-generate product description from sales page content
  const autoDescribe = async (salesContent) => {
    if (!salesContent || salesContent.length < 50) return;

    setDescribing(true);
    try {
      const result = await api.autoDescribe(salesContent);
      setForm(prev => ({ ...prev, product_description: result.description }));
      setDescAutoGenerated(true);
    } catch (err) {
      // Non-blocking — if it fails, user can still type manually
      console.warn('Auto-describe failed:', err.message);
    } finally {
      setDescribing(false);
    }
  };

  // Trigger auto-describe when switching from paste mode (after user pastes content)
  const handleSalesContentBlur = () => {
    if (form.sales_page_content && !form.product_description) {
      autoDescribe(form.sales_page_content);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const project = await api.createProject(form);
      navigate(`/projects/${project.id}`);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Layout>
      <div className="max-w-2xl mx-auto fade-in">
        <div className="mb-6">
          <h1 className="text-2xl font-semibold text-textdark tracking-tight">New Project</h1>
          <p className="text-[13px] text-textmid mt-0.5">Set up a new ad creative project</p>
        </div>

        {error && (
          <div className="bg-red-50/80 border border-red-200/60 text-red-600 text-[13px] rounded-xl p-3 mb-4">
            {error}
          </div>
        )}

        <form onSubmit={handleSubmit} className="card p-6 space-y-5">
          {/* Project Name */}
          <div>
            <label className="block text-[13px] font-medium text-textmid mb-1.5">
              Project Name <span className="text-red-400">*</span>
            </label>
            <input
              name="name"
              value={form.name}
              onChange={handleChange}
              className="input-apple"
              required
              placeholder="e.g., Brain Supplement Launch"
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-[13px] font-medium text-textmid mb-1.5">Brand Name</label>
              <input
                name="brand_name"
                value={form.brand_name}
                onChange={handleChange}
                className="input-apple"
                placeholder="e.g., NeuroVitality"
              />
            </div>
            <div>
              <label className="block text-[13px] font-medium text-textmid mb-1.5">Niche</label>
              <input
                name="niche"
                value={form.niche}
                onChange={handleChange}
                className="input-apple"
                placeholder="e.g., Nootropics / Brain Health"
              />
            </div>
          </div>

          {/* Sales Page Content */}
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="block text-[13px] font-medium text-textmid">Sales Page Content</label>
              <div className="segmented-control">
                <button
                  type="button"
                  onClick={() => setSalesInputMode('upload')}
                  className={salesInputMode === 'upload' ? 'active' : ''}
                >
                  Upload PDF
                </button>
                <button
                  type="button"
                  onClick={() => setSalesInputMode('paste')}
                  className={salesInputMode === 'paste' ? 'active' : ''}
                >
                  Paste Text
                </button>
              </div>
            </div>

            {salesInputMode === 'upload' ? (
              <div>
                <DragDropUpload
                  label="Drop your PDP / Sales Page here, or click to browse"
                  sublabel="PDF, TXT, or HTML — we'll extract the text content"
                  onTextExtracted={(result) => {
                    setForm(prev => ({ ...prev, sales_page_content: result.text }));
                    setUploadedFile({ name: result.filename, charCount: result.charCount });
                    autoDescribe(result.text);
                  }}
                  successMessage={uploadedFile ? `${uploadedFile.name} (${uploadedFile.charCount.toLocaleString()} chars)` : undefined}
                  status={uploadedFile ? 'success' : undefined}
                />
                {/* Show extracted content preview */}
                {form.sales_page_content && uploadedFile && (
                  <div className="mt-3">
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-[12px] text-textlight">Extracted content preview</span>
                      <button
                        type="button"
                        onClick={() => setSalesInputMode('paste')}
                        className="text-[12px] text-gold hover:text-gold-light transition-colors"
                      >
                        Edit text
                      </button>
                    </div>
                    <div className="bg-offwhite border border-black/5 rounded-xl p-3 max-h-32 overflow-y-auto text-[12px] text-textmid whitespace-pre-wrap scrollbar-thin">
                      {form.sales_page_content.slice(0, 1000)}
                      {form.sales_page_content.length > 1000 ? '...' : ''}
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <div>
                <textarea
                  name="sales_page_content"
                  value={form.sales_page_content}
                  onChange={handleChange}
                  onBlur={handleSalesContentBlur}
                  rows={8}
                  className="input-apple resize-none"
                  placeholder="Paste the text content from your sales page here..."
                />
              </div>
            )}
          </div>

          {/* Product Description */}
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="block text-[13px] font-medium text-textmid">Product Description</label>
              {describing && (
                <span className="text-[12px] text-gold animate-pulse">Generating from sales page...</span>
              )}
              {descAutoGenerated && !describing && (
                <span className="text-[12px] text-teal flex items-center gap-1">
                  <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                  AI-generated
                </span>
              )}
            </div>
            <textarea
              name="product_description"
              value={form.product_description}
              onChange={handleChange}
              rows={3}
              className={`input-apple resize-none ${
                descAutoGenerated ? 'border-teal/30 bg-teal/5' : ''
              }`}
              placeholder={form.sales_page_content
                ? 'Will be auto-generated from your sales page content...'
                : 'Add sales page content first, or type a description manually'}
            />
            {!form.product_description && form.sales_page_content && !describing && (
              <button
                type="button"
                onClick={() => autoDescribe(form.sales_page_content)}
                className="text-[12px] text-gold hover:text-gold-light mt-1.5 transition-colors"
              >
                Generate description from sales page
              </button>
            )}
          </div>


          <div className="flex gap-3 pt-2">
            <button
              type="submit"
              disabled={loading}
              className="btn-primary"
            >
              {loading ? 'Creating...' : 'Create Project'}
            </button>
            <button
              type="button"
              onClick={() => navigate('/')}
              className="btn-secondary"
            >
              Cancel
            </button>
          </div>
        </form>
      </div>
    </Layout>
  );
}
